build:
  environment:
    php:
      version: 7.4
  tests:
    before:
      - yarn encore dev
    override:
      - command: vendor/bin/phpunit --coverage-clover=coverage.xml
        coverage:
          file: coverage.xml
          format: php-clover
