build:
  environment:
    php:
      version: 7.4
  tests:
    override:
      -
        command: ./bin/phpunit --coverage-clover=coverage.xml
        coverage:
          file: coverage.xml
          format: php-clover
